[build]
  command = "yarn build"
  publish = "dist"

  [[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
