[build]
  command = "yarn build"
  publish = "dist"

  # [[redirects]]
  #   from = "from_link"
  #   to = "notion_link"
  #   status = 301
  #   force = true

  ## more info on configuring this file: https://www.netlify.com/docs/netlify-toml-reference/
